
<?php

include_once('includes/head.php');

$a_multi_comentarios = array('20200903225522'=> array( 'id_producto' => '1', 'mail'=>'1@gmail.com','comentario'=>'Es uno de los mejores libros de la saga, junto con el tres y el siete, es un formato mucho más largo y complejo, la historia tiene mucho más detalles que la otra, pero por eso no deja de ser entretenida, incluso, se llegan a tocar temas mucho más serios y profundos, como la muerte, la traición, etc, etc. Es un libro estupendo, lo recomiendo ampliamente.', 'valoracion' => '5'),
                             '20200903225524'=> array( 'id_producto' => '1', 'mail'=>'1@gmail.com','comentario'=>'La saga Potter crece a la par que el lector y profundiza en los personajes, sus conflictos y sus historias individuales. Sin embargo, al intentar variar aquello que le salió tan bien en las primeras entregas y darle un matiz más oscuro y adulto (que incluso se acerca al terror) J. K. Rowling iría perdiendo espontaneidad hasta írsele la saga de las manos. Sin ir más lejos, aspectos como el del enamoramiento y el paso de la infancia a la adolescencia de Potter los encuentro muy poco logrados. Magia, fantasía y aventuras que no falten.', 'valoracion' => '3'),
                             '20200903225520'=> array( 'id_producto' => '1', 'mail'=>'1@gmail.com','comentario'=>'Este cuarto libro inicia la maduración de la saga, pensando tal vez en el crecimiento de los lectores, ademas cuenta con la competición que le da un ritmo ameno respecto a los anteriores libros. Que buen ritmo para contar la historia tiene la autora para no hacerlo pesado.', 'valoracion' => '4'),
                             '20200903225523'=> array( 'id_producto' => '1', 'mail'=>'1@gmail.com','comentario'=>'La verdad es que es un pequeño paso atrás en calidad respecto al anterior por que la autora le da demasiada importancia (y páginas) al Torneo y no a la trama principal de la historia. Aun así el final es tan épico y fantástico que te deja con un gran sabor de boca, y deseando leer más.', 'valoracion' => '4'),
                             '20200903225522'=> array( 'id_producto' => '2', 'mail'=>'1@gmail.com','comentario'=>'En la línea de sus predecesoras, emocionante y emotiva, combinando los sentimientos y pasiones de los protagonistas con las fabulosas aventuras en esta nueva tierra. Pero siendo ya una seguidora incondicional de esta saga, me decepcionó un poco como se desarrolló la llegada de Brianna. Creo que la autora no le sacó todo el partido posible a lo que podría haber sido un encuentro realmente emotivo con sus padres y se centró más en las adversidades de su relación con Roger, la que tampoco está a la altura de lo que Diana Gabaldón nos tenía acostumbrados, sobre todo porque en esta entrega pasan a tener un protagonismo equivalente al de Jaimie y Claire. Sin embargo, sigue siendo una novela maravillosa, con un estilo narrativo inmejorable que te mantiene completamente atrapado en sus páginas.', 'valoracion' => '5'),
                             '20200903225524'=> array( 'id_producto' => '2', 'mail'=>'1@gmail.com','comentario'=>'La historia de los protagonistas, Jamie y Claire decae un poco en detrimento de la de su hija Brianna y Roger, y aunque es un poco más "tranquila" que las anteriores entregas, sigue siendo muy entrenida.', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '2', 'mail'=>'1@gmail.com','comentario'=>'Al igual que los anteriores de la saga la lectura de este libro te hace desear en algún momento compartir todas las aventuras que viven los protagonistas.', 'valoracion' => '4'),
                             '20200903225523'=> array( 'id_producto' => '2', 'mail'=>'1@gmail.com','comentario'=>'Esta saga, a pesar de tantas buenas críticas, la abandoné hace tiempo y aunque parezca imposible, sigo disfrutando de la historia con la serie. Qué sin duda, y es mi humilde opinión, es superior a esta. Retomé la lectura con este libro, llevada por las ansias de conocer el desenlace de la temporada, y sigo opinando lo mismo; se extiende demasiado y no consigue que la lectura me atrape, me esfuerzo por acabar los libros.', 'valoracion' => '3'),
                             '20200903225522'=> array( 'id_producto' => '3', 'mail'=>'1@gmail.com','comentario'=>'La trama es muy sencilla igual que la investigación que me parece más una excusa para desarrollar al personaje principal y para realizar una muy buena ambientación sobre el Valle de Aosta. La novela me ha resultado entretenida sobre todo por el giro del guión que desarrolla matices más duros y personales de la historia.', 'valoracion' => '3'),
                             '20200903225524'=> array( 'id_producto' => '3', 'mail'=>'1@gmail.com','comentario'=>'Muy entretenida, aunque me gustó más la primera novela. A mi parecer, le falta algo más de acción. Aun así, totalmente recomendable por el humor y ‘el valle de Aosta’.', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '3', 'mail'=>'1@gmail.com','comentario'=>'Muy entretenido y divertido. Se lee muy fácilmente. El personaje protagonista es total.', 'valoracion' => '4'),
                             '20200903225523'=> array( 'id_producto' => '3', 'mail'=>'1@gmail.com','comentario'=>'Segundo libro de la serie Rocco Schiavone. Lo recomiendo absolutamente. Hay espacio incluso para el humor.', 'valoracion' => '4'),
                             '20200903225522'=> array( 'id_producto' => '4', 'mail'=>'1@gmail.com','comentario'=>'Una novela corta, entretenida y muy agradable de leer nuevos episodios de Montalbano.', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '4', 'mail'=>'1@gmail.com','comentario'=>'"La Voz del violín" es la típica novela que te llevas a un viaje de 10 días. Pequeña, entretenida, personaje principal muy bien caracterizado y una historia a ratos intrigante, a ratos irónica... Un libro como cientos de miles. Si lo lees, ni te decepcionará, ni te apasionará. En mi humilde pero objetiva opinión. Un saludo!', 'valoracion' => '2'),
                             '20200903225520'=> array( 'id_producto' => '4', 'mail'=>'1@gmail.com','comentario'=>'Un caso más del comisario Montalbano, divertido, rápido de leer y sin complicaciones.', 'valoracion' => '3'),
                             '20200903225523'=> array( 'id_producto' => '4', 'mail'=>'1@gmail.com','comentario'=>'Cuarta entrega de Montalbano, que sigue desvelando al lector facetas desconocidas de su personalidad, que lo hacen cada vez más cercano y admirable. Es muy interesante la relación que mantiene con sus subordinados, un muy divertido grupo de policías de Vigàta, ante el que Camilleri desata su aguda ironía sin piedad. Sicilia, su gastronomía y sus gentes, siguen muy presentes en toda la obra, marcada por los numerosos cambios de personal en la jefatura policial y en los científicos forenses, que obligan a Salvo a lidiar con más obstáculos de los deseados. Muy buena novela.', 'valoracion' => '5'),
                             '20200903225522'=> array( 'id_producto' => '5', 'mail'=>'1@gmail.com','comentario'=>'Está entretenido e interesante. El libro está escrito de manera sencilla, pero como habla de mitología griega a veces puede sonar un poco complicado. Aprendes mucho sobre las creencias, heroés y dioses en los que creían. Puedes llegar a identificarte con las personalidades de los personajes. Las aventuras que tienen los personajes hace la lectura fascinante. Cada libro de la saga tiene una parte que te sorprende ya que esperabas otra cosa. A mi en lo personal me ha gustado mucho porque he llegado a encariñarme con los personajes por el hecho de que son muchos libros.', 'valoracion' => '3'),
                             '20200903225524'=> array( 'id_producto' => '5', 'mail'=>'1@gmail.com','comentario'=>'Es una buena continuacion y el final me ha dejado impresionado, pero convencido que las peliculas son malas.', 'valoracion' => '3'),
                             '20200903225520'=> array( 'id_producto' => '5', 'mail'=>'1@gmail.com','comentario'=>'El libro es muy divertido y es interesante si te gusta la mitologia griega y tenes un cierto conocimiento de los hechos y personajes que nombra. Pero por otra parte el estilo es demasiado simple lo que convierte en una copia mitologica de Harry Potter', 'valoracion' => '2'),
                             '20200903225523'=> array( 'id_producto' => '5', 'mail'=>'1@gmail.com','comentario'=>'Diré cosas que a los seguidores de Percy Jackson les molestará, pero este libro es bastante simple. La historia es normalita y sólo le salva el curioso final. Además, las numerosas similitudes de esta saga con la de Harry Potter hacen cuestionarme la originalidad de la serie...Prescindible.', 'valoracion' => '1'),
                             '20200903225522'=> array( 'id_producto' => '6', 'mail'=>'1@gmail.com','comentario'=>'Excelente libro. Mezcla futbol, amistad y negocios. Me parecen fantasticas las conversaciones entre los amigos y los pensamientos de cada uno sobre el otro. Te atrapa en todo momento. Llega un punto en el que no podes parar de leer.', 'valoracion' => '5'),
                             '20200903225524'=> array( 'id_producto' => '6', 'mail'=>'1@gmail.com','comentario'=>'Me gusto mucho el libro y la forma de escribir de Sacheri. Se me hizo una lectura rapida y me divirtio muchola camaraderia de los amigos (algo que siempre envidie de los hombres) y la pasion del futbol. Ahora voy a ver la pelicula a ver que tal la adaptacion.', 'valoracion' => '5'),
                             '20200903225520'=> array( 'id_producto' => '6', 'mail'=>'1@gmail.com','comentario'=>'Una ternura absoluta de libro. Siempre Sacheri la dulzura justa. De todas maneras, este es sin duda su mejor libro.', 'valoracion' => '5'),
                             '20200903225523'=> array( 'id_producto' => '6', 'mail'=>'1@gmail.com','comentario'=>'Una gran historia la que nos cuenta Sacheri, con mucho fútbol, lealtad, compromiso y sobre todo amistad. Se lee fácil y no te aburre en ningún momento.', 'valoracion' => '5'),
                             '20200903225522'=> array( 'id_producto' => '7', 'mail'=>'1@gmail.com','comentario'=>'La historia es muy sencilla, casi cotidiana pero lo importante es la magnífica narración que hace Sacheri. Me ha encantado la ambientación, la descripción de personajes, la trama, el ritmo, el estilo literario…Lo peor :Me han sobrado algunas largas conversaciones referidas al contexto histórico.Lo mejor:Como el autor logra introducirte en la historia para no dejarte salir hasta que terminas el libro. Muy bueno!', 'valoracion' => '5'),
                             '20200903225524'=> array( 'id_producto' => '7', 'mail'=>'1@gmail.com','comentario'=>'Excelente Sacheri, como siempre. La historia me resultó atrapante desde el principio y me sorprendió mucho como encarna la trama desde la protagonista mujer. Muy buenas referencias históricas para situar al lector en la tumultosa Argentina post-peronismo. Muy recomendable.', 'valoracion' => '5'),
                             '20200903225520'=> array( 'id_producto' => '7', 'mail'=>'1@gmail.com','comentario'=>'Me ha gustado mucho. Una historia que al principio parece intrascendente pero que la maestría de Sacheri hace que te enganche con su hábil manejo de situaciones y personajes y en este caso, además, se mete en el alma y la piel de su protagonista, una voz femenina, que nos transmite sin paliativos todos sus sentimientos, carencias, dudas, pensamientos, contradicciones… Me han sobrado un poco las frecuentes conversaciones y discusiones sobre la política de Argentina en los años 50/60, pero en general es una novela amena , bien construída y excelentemente narrada.', 'valoracion' => '5'),
                             '20200903225523'=> array( 'id_producto' => '7', 'mail'=>'1@gmail.com','comentario'=>'Linda historia de una familia tipo de clase media de los 50 en argentina. Entretenida, con un dilema moral, un amor inapropiado y un final excelente e inesperado. A mi Criterio Un poco aburridos los capítulos que charlan y discuten de política pero buena historia', 'valoracion' => '3'),
                             '20200903225522'=> array( 'id_producto' => '8', 'mail'=>'1@gmail.com','comentario'=>'Excelente como toda la obra de bodoc', 'valoracion' => '5'),
                             '20200903225524'=> array( 'id_producto' => '8', 'mail'=>'1@gmail.com','comentario'=>'La historia es interesante y familiar, al menos para los latinoamericanos. Por momentos la narrativa es muy lenta, hay capítulos que realmente te dan ganas de no leerlos y pasar directo a la acción, pero todo es parte de la gestación de la revolución que se da en la historia, y ninguna revolución se hace de la noche a la mañana. Está bien pero no es tan atrapante como otros libros de la autora.', 'valoracion' => '3'),
                             '20200903225520'=> array( 'id_producto' => '8', 'mail'=>'1@gmail.com','comentario'=>'Me pareció un verdadero bodrio', 'valoracion' => '1'),
                             '20200903225523'=> array( 'id_producto' => '8', 'mail'=>'1@gmail.com','comentario'=>'No ha sabido capturar las letras como en otras de sus obras, pero aun asi me parece un libro recomendable.', 'valoracion' => '2'),
                             '20200903225522'=> array( 'id_producto' => '9', 'mail'=>'1@gmail.com','comentario'=>'Esta es una novela rara. No tiene un plot que te vuele la cabeza y en general los libros en los que no pasa nada me terminan embolando y los dejo, pero la poética con que Silvia te va narrando todo eso hace que estés enganchado y encuentres belleza en las metáforas, en las pequeñas cosas que nos presenta y terminemos encariñándonos del personaje. Una novela de iniciación muy bella.', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '9', 'mail'=>'1@gmail.com','comentario'=>'Fantástica novela. La adolescencia en el extranjero, la adolescencia de las palabras, de las amistades, de los romances. Todo con dulce de leche en lata.', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '9', 'mail'=>'1@gmail.com','comentario'=>'Gran libro! La forma de escribir de la autora es atrapante y me hizo recordar algunos momentos de mi adolescencia.', 'valoracion' => '5'),
                             '20200903225523'=> array( 'id_producto' => '9', 'mail'=>'1@gmail.com','comentario'=>'Si bien prefiero otro tipo de lecturas, este libro fue muy entretenido.', 'valoracion' => '3'),
                             '20200903225522'=> array( 'id_producto' => '10','mail'=>'1@gmail.com', 'comentario'=>'En esta nueva novela , la escritora aborda el tema del aborto en un marco familiar de profunda ortodoxia religiosa. El nudo narrativo gira en torno a ese aparente crimen no resuelto, que en realidad esconde un sinnúmero de sucesos causados por el dominio de ciertos prejuicios y valores dogmáticos . Cada protagonista da su versión ‘verosímil’ , trata de justificar en cierto modo sus propias actitudes y decisiones. En definitiva, casi todos tratan de desligarse lo más posible de sus propios demonios y evitar que la culpa actúe como una filosa espada de Damocles. Si bien pueden notarse ciertos estereotipos y algunas situaciones tal vez un tanto inverosímiles, la novela construye logradas relaciones conflictivas y la narración es ágil y engancha.', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '10','mail'=>'1@gmail.com', 'comentario'=>'Una novela que me atrapó desde el primer momento. De esas que invitan a "devorar" y cada hoja te atrapa un poco más. El final se puede anticipar con el correr de los capítulos pero no por eso deja de ser atrapante. Bien escrita. Con un ida y vuelta del presente al pasado. Muy interesante', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '10','mail'=>'1@gmail.com', 'comentario'=>'Catedrales es un libro en el que todo gira alrededor de un asesinato no resuelto cometido hace 30 años. A través de varios personajes involucrados se van desvelando hechos que nos dan una clara visión de lo que pasó. No es una novela con grandes sorpresas, enseguida se adivina lo sucedido, pero tampoco lo pretende. Se centra más en los personajes, en su relación y cómo les ha afectado la muerte de Ana. Muy buen libro para disfrutar de una prosa intimista y unos personajes potentes. Recomendado.', 'valoracion' => '4'),
                             '20200903225523'=> array( 'id_producto' => '10','mail'=>'1@gmail.com', 'comentario'=>'No empiecen este libro buscando un policial o un thriller porque no van a encontrar misterio y probablemente sientan predecible la cantidad de información con la que, como lectores, contamos en todo momento. Lo interesante y cautivante desde el inicio de esta novela es el realismo de los temas que toca, es como la autora se anima a hablar sin ser políticamente correcta acerca de religión, creencias, vínculos familiares, mentiras, entre tantos otros tópicos que no quiero adelantar para que los descubran de a poco y para que experimenten con el cuerpo la cantidad de emociones que el libro produce.', 'valoracion' => '4'),
                             '20200903225522'=> array( 'id_producto' => '11','mail'=>'1@gmail.com', 'comentario'=>'Volumen muy recomendable.', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '11','mail'=>'1@gmail.com', 'comentario'=>'Es una de las mejores obras de Nabokov, para mí mejor incluso que Lolita, y disfruté mucho leyendo ambos...', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '11','mail'=>'1@gmail.com', 'comentario'=>'770 páginas de Nabokov cuentista, flojos abstenerse!', 'valoracion' => '5'),
                             '20200903225523'=> array( 'id_producto' => '11','mail'=>'1@gmail.com', 'comentario'=>'Un placer para los sentidos!!', 'valoracion' => '5'),
                             '20200903225522'=> array( 'id_producto' => '12','mail'=>'1@gmail.com', 'comentario'=>'Arundhati Roy prueba que es una pensadora apasionada, inteligente y documentada', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '12','mail'=>'1@gmail.com', 'comentario'=>'‘Mi corazón sedicioso’ es una recopilación de escritos políticos de Arundhati Roy.', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '12','mail'=>'1@gmail.com', 'comentario'=>'Leerla siempre es estimulante por más que en ocasiones sus juicios puedan resultar demasiado sumarísimos, por ejemplo los que se refieren en abstracto a la democracia liberal. ', 'valoracion' => '3'),
                             '20200903225523'=> array( 'id_producto' => '12','mail'=>'1@gmail.com', 'comentario'=>'Da la sensación de que todo resulta más certero y particularmente inapelable cuando la autora se ocupa de asuntos concretos y cercanos a su realidad.', 'valoracion' => '2'),
                             '20200903225522'=> array( 'id_producto' => '13','mail'=>'1@gmail.com', 'comentario'=>'Primer libro que leo de esta autora y me dejo con ganas de más. Desgarradora página a página. Simple. Breve. Dura. Se lee de un tirón. Muy recomendable. No es una novela de mujeres es una novela para mujeres.', 'valoracion' => '5'),
                             '20200903225524'=> array( 'id_producto' => '13','mail'=>'1@gmail.com', 'comentario'=>'Delicada disección del corazón de algunas madrastras de blancanieves. Novela lúcida de la no siempre, saludable relación madre e hija. Y llegadxs a este punto me pregunto: por qué el psicoanálisis no nos ha dejado un nombre para éste fenómeno como lo hizo con Edipo o Electra? O por qué la Biblia, rebosante de héroes y villanxs no nos deja muestras de este conflicto humano? Por qué en definitiva, las mujeres a estas alturas del S XXI debemos elaborar nuestra propia cosmogonía?', 'valoracion' => '5'),
                             '20200903225520'=> array( 'id_producto' => '13','mail'=>'1@gmail.com', 'comentario'=>'Lo encontré de casualidad y me llamó la atención el titulo y el precio barato. Realmente fue un descubrimiento exquisito. Es un libro bello. La historia, los personajes y los diálogos, concretos y consisos, muy bien logrados. Sencillo pero sumamente bien escrito. Hermoso final. Buscaré más libros de la autora.', 'valoracion' => '4'),
                             '20200903225523'=> array( 'id_producto' => '13','mail'=>'1@gmail.com', 'comentario'=>'Entretenida historia sobre la pasión, el amor infantil y la guerra. Se deja leer.', 'valoracion' => '3'),
                             '20200903225522'=> array( 'id_producto' => '14','mail'=>'1@gmail.com', 'comentario'=>'Literatura alcohólica, en ocasiones más bien diabólica, para un conjunto de relatos cortos sobre marginalidad y malditismo.', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '14','mail'=>'1@gmail.com', 'comentario'=>'Irregular selección de relatos. En principio hay muchos con sexo y violencia, bastante flojitos, incluso alguno me ha molestado, no me parece divertida la violencia contra las mujeres. Después mejora con algunos cuentos mas realistas protagonizados por Chinaski que están bastante bien. Pero es solo al final, con los tres últimos relatos, mas largos y todos de Chinaski, cuando me he reencontrado con todo el sabor ácido y amargo del Bukowski que tanto me gusta. Me he divertido especialmente con aquel en que Hank narra su operación de hemorroides, todo su sufrimiento al tener que soportar a sus compañeros de habitación y lo que es peor, aguantar la tele.', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '14','mail'=>'1@gmail.com', 'comentario'=>'Morador del underground, da una mirada corrosiva y cáustica de la vida. Horada con mordacidad y provocación el sórdido universo del que el propio autor es protagonista.', 'valoracion' => '4'),
                             '20200903225523'=> array( 'id_producto' => '14','mail'=>'1@gmail.com', 'comentario'=>'Bukowski en su maxima expresion. Siempre es un gusto encontrarlo.', 'valoracion' => '5'),
                             '20200903225522'=> array( 'id_producto' => '15','mail'=>'1@gmail.com', 'comentario'=>'Excepcional obra -una vez más, aunque seguramente habría que plantear "Mi lucha" como bloque inseparable- de un autor que aporta fuerza y frescura a un panorama internacional excesivamente cargado de intelectualismo formal. Las obras de Knausgard no se leen, se viven, se palpan, se siente en la piel y en lo más hondo de las entrañas. Indiscutiblemente, una obra maestra de nuestro tiempo.', 'valoracion' => '5'),
                             '20200903225524'=> array( 'id_producto' => '15','mail'=>'1@gmail.com', 'comentario'=>'Para mí de los que he leído-hasta el cuarto- tal vez sea el más flojo. Es una saga bien escrita, aunque por lo ambiciosa esperaba mucho más.', 'valoracion' => '2'),
                             '20200903225520'=> array( 'id_producto' => '15','mail'=>'1@gmail.com', 'comentario'=>'Igual que con el primer volumen, se va leyendo, nada se avanza a nivel argumental, pasa de una situación a otra y a otra sin resolver ninguna, el argumento sigue sin avanzar, te pierdes (al menos yo) con sus discusiones filosóficas... pero no puedes dejar de leerlo.' , 'valoracion' => '3'),
                             '20200903225523'=> array( 'id_producto' => '15','mail'=>'1@gmail.com', 'comentario'=>'Quizás es porque te sientes identificado con sus situaciones cotidianas, con sus frustraciones, con sus alegrías. Describe una vida con sus medianías, sus momentos buenos y sobre todo ese poso de frustración perpetua que nos atenaza. No sé si continuaré con la serie', 'valoracion' => '1'),
                             '20200903225522'=> array( 'id_producto' => '16','mail'=>'1@gmail.com', 'comentario'=>'El libro es bueno, pero se hace un poquito extenso.', 'valoracion' => '3'),
                             '20200903225524'=> array( 'id_producto' => '16','mail'=>'1@gmail.com', 'comentario'=>'Si bien esta historia llegó a tener mucho reconocimiento por la película, considero que el libro está al menos entre los 3 mejores del autor. como único punto negativo: Los pasajes en que cuenta apariciones antiguas del payaso (como en el tiroteo o la fábrica) sirven y ayudan a comprender mejor todo, pero se hacen un poco densos. El punto que más resalto: La construcción de los lugares y personajes. Cuando vi la última película tenía más expectativa por saber como iban a representar a Derry y los Barrens que de ver la peli en si', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '16','mail'=>'1@gmail.com', 'comentario'=>'Me ha costado muchísimo terminarlo. El principio del libro (las primeras 600 páginas) se me han hecho larguísimas, hasta que le he pillado el ritmo., Me molestan mucho los libros que dan tantos saltos temporales para contar dos historias paralelas, una en el presente y otra en el pasado, como en este caso. Personalmente prefiero que me cuenten la historia del pasado primero y la historia del presente después, máxime cuando no hay ninguna necesidad de ocultarla, pues nada de lo que ocurre en el pasado le puede quitar emoción a lo que ocurre en el presente. Es un recurso literario muy pobre que se ha puesto muy de moda (y ahora no lo digo por el Sr. King, que posiblemente fuera de los primeros en utilizarlo), pues se basa en la ocultación de información al lector, cosa que me molesta muchísimo, pues me siento tratado como un tonto.', 'valoracion' => '1'),
                             '20200903225523'=> array( 'id_producto' => '16','mail'=>'1@gmail.com', 'comentario'=>'Una historia fantástica, con excelentes personajes y un canto a la amistad. Un poco flojo el final pero igual no deja de redondear una gran novela.', 'valoracion' => '4'),
                             '20200903225522'=> array( 'id_producto' => '17','mail'=>'1@gmail.com', 'comentario'=>'Es un buen libro, de aventuras, divertido, con muchos contrastes entre los personajes e historias con mucha imaginación. Sobre todo es un libros o libros (porque son 3) para adolescentes.; pero como adultos tambien puedes disfrutar.', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '17','mail'=>'1@gmail.com', 'comentario'=>'Tres aventuras fantasticas, en la selva amazonica, en un reino enclavado en la cordillera del Himalaya, y en el corazon de Africa, maravillosa', 'valoracion' => '5'),
                             '20200903225520'=> array( 'id_producto' => '17','mail'=>'1@gmail.com', 'comentario'=>'Es muy interesante y divertido.Recomiendo leerlo', 'valoracion' => '4'),
                             '20200903225523'=> array( 'id_producto' => '17','mail'=>'1@gmail.com', 'comentario'=>'buenisimo...', 'valoracion' => '4'),
                             '20200903225522'=> array( 'id_producto' => '18','mail'=>'1@gmail.com', 'comentario'=>'Un libro para el que hay que tener ganas de leerlo, si no se hace pesado y tedioso. Me gusta más la segunda parte (diario de viajes) que la primera. Estoy contento con la compra :)', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '18','mail'=>'1@gmail.com', 'comentario'=>'Es un tipico libro Kafkiano', 'valoracion' => '3'),
                             '20200903225520'=> array( 'id_producto' => '18','mail'=>'1@gmail.com', 'comentario'=>'Encantada con esta maravilla de la literatura. Amo la forma de escribir de Kafka. Desde que lei "La metamorfosis" no puedo parar de leerlo.', 'valoracion' => '5'),
                             '20200903225523'=> array( 'id_producto' => '18','mail'=>'1@gmail.com', 'comentario'=>'Es un libro muy raro.', 'valoracion' => '2'),
                             '20200903225522'=> array( 'id_producto' => '19','mail'=>'1@gmail.com', 'comentario'=>'Lectura agradable y amena, entretenida', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '19','mail'=>'1@gmail.com', 'comentario'=>'Un gran clásico de la literatura y por derecho propio, poco más se puede decir. Muy recomendable, sobre todo la primera parte que narra la infancia del protagonista, para mi gusto lo más potente del libro.', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '19','mail'=>'1@gmail.com', 'comentario'=>'Es fabulosa la narrativa. El detalle a ultranza, la evocación de escenas, situaciones, personajes.. todo juega y suma en esta obra. No soy de clásicos pero este es sin duda un imperdible.', 'valoracion' => '3'),
                             '20200903225523'=> array( 'id_producto' => '19','mail'=>'1@gmail.com', 'comentario'=>'Creo que es un clásico infravalorado, sin duda uno de mis libros favoritos de Dickens', 'valoracion' => '2'),
                             '20200903225522'=> array( 'id_producto' => '20','mail'=>'1@gmail.com', 'comentario'=>'Me gustó mucho, para mi parecer: aquí hubiera terminado la historia de Tatiana y Alexander. El jardín de verano fué innecesario, a mi gusto me resultó pesado terminarlo.', 'valoracion' => '2'),
                             '20200903225524'=> array( 'id_producto' => '20','mail'=>'1@gmail.com', 'comentario'=>'muy recomendable, de fácil lectura, una historia muy conmovedora que no paras de leer', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '20','mail'=>'1@gmail.com', 'comentario'=>'está bien, sobre todo me ha gustado la parte de alexander pero el primero era precioso.', 'valoracion' => '4'),
                             '20200903225523'=> array( 'id_producto' => '20','mail'=>'1@gmail.com', 'comentario'=>'Vaya pedazo de segunda parte para El Jinete de Bronce. MARAVILLOSO', 'valoracion' => '5'),
                             '20200903225522'=> array( 'id_producto' => '21','mail'=>'1@gmail.com', 'comentario'=>'Como siempre la autora nos lleva a la epoca y conocemos de nuestra historia de manera amena', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '21','mail'=>'1@gmail.com', 'comentario'=>'Si bien el libro se explaya en acontecimientos conocidos, el verdadero sentir de Belgrano esta muy bien relatado, haciendonos ver el lado humano del procer. ', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '21','mail'=>'1@gmail.com', 'comentario'=>'Excelente. Altamente recomendable.', 'valoracion' => '5'),
                             '20200903225523'=> array( 'id_producto' => '21','mail'=>'1@gmail.com', 'comentario'=>'Otra obra maestra de Canale.', 'valoracion' => '5'),
                             '20200903225522'=> array( 'id_producto' => '22','mail'=>'1@gmail.com', 'comentario'=>'En la línea del autor, que siempre nada en las mismas aguas. Es interesante, pero sobre todo te despierta las ganas de pasarte por El Prado y buscar todas las obras que menciona, y observarlas.', 'valoracion' => '4'),
                             '20200903225524'=> array( 'id_producto' => '22','mail'=>'1@gmail.com', 'comentario'=>'Esperaba algo mas....me ha dejado un poco decepcionada.He aprendido algo más del arte pictórico,eso si que es cierto,pero insisto un poco decepcionada Un saludo' , 'valoracion' => '2'),
                             '20200903225520'=> array( 'id_producto' => '22','mail'=>'1@gmail.com', 'comentario'=>'Una pequeña decepción, esperaba mucho más de este libro. Su mayor logro es aportar datos desconocidos de los cuadros, despertando la curiosidad, pero poco más.' , 'valoracion' => '2'),
                             '20200903225523'=> array( 'id_producto' => '22','mail'=>'1@gmail.com', 'comentario'=>'Las 3/4 partes del libro son buenas, pero en los capítulos finales la trama es complicdísima de seguir y desde luego el final es impropio de una novela de la que esperaba muchísimo más.', 'valoracion' => '2'),
                             '20200903225522'=> array( 'id_producto' => '23','mail'=>'1@gmail.com', 'comentario'=>'Fabuloso, con una música y unos interpretes maravillosos.', 'valoracion' => '5'),
                             '20200903225524'=> array( 'id_producto' => '23','mail'=>'1@gmail.com', 'comentario'=>'Me encanto. La música es impresionante, y el autor supo elegir a los intérpretes de su obra. Hago mención especial a Mercedes Sosa como La Pitonisa, estuvo brillante.', 'valoracion' => '5'),
                             '20200903225520'=> array( 'id_producto' => '23','mail'=>'1@gmail.com', 'comentario'=>'Una historia muy bella entre fantasía y realidad sobre lo que es el amor. Me ha dejado un buen sabor de boca.', 'valoracion' => '4'),
                             '20200903225523'=> array( 'id_producto' => '23','mail'=>'1@gmail.com', 'comentario'=>' yo no me olvido de nada, el olvido es para los que se van sin pagar. Yo ya pagué', 'valoracion' => '5'),
                             '20200903225522'=> array( 'id_producto' => '24','mail'=>'1@gmail.com', 'comentario'=>'Es entretenido pero trata el tema del sexo de una manera burda y vasta(eso me parece a mi), el final ha quedado un poco abierto por lo que me temo que habrá más, pero yo no pienso leerlo, vamos que lo considero totalmente prescindible.', 'valoracion' => '2'),
                             '20200903225524'=> array( 'id_producto' => '24','mail'=>'1@gmail.com', 'comentario'=>'De este libro me gusto la idea, una sociedad secreta para mujeres, creo que se podía haber sacado más jugo, pero la historia de la protagonista engancha. Me ha parecido entretenido, divertido y ameno. Tengo que decir que me ha parecido bastante más profundo que el sexo, es más de superación personal, aceptación de uno mismo, recuperar la confianza perdida y liberación.', 'valoracion' => '4'),
                             '20200903225520'=> array( 'id_producto' => '24','mail'=>'1@gmail.com', 'comentario'=>'Atrapa casi desde la primera página, entretiene mucho y es seductor. ', 'valoracion' => '5'),
                             '20200903225523'=> array( 'id_producto' => '24','mail'=>'1@gmail.com', 'comentario'=>'Impaciente por continuar la serie.', 'valoracion' => '5'),
                            
                            );

                            print_r($a_multi_comentarios);



                            $comentarios = array(   '20200903225522'=> array ('id_producto'=>'1','correo'=>'1@correo.com', 'comentario'=>'muy bueno', 'valoracion'=>'5'),
                                                    '20200903225524'=> array ('id_producto'=>'1','correo'=>'2@correo.com', 'comentario'=>'muy malo', 'valoracion'=>'1'),
                                                    '20200903225520'=> array ('id_producto'=>'2','correo'=>'1@correo.com', 'comentario'=>'bueno', 'valoracion'=>'3'),
                                                    '20200903225521'=> array ('id_producto'=>'2','correo'=>'1@correo.com', 'comentario'=>'regular', 'valoracion'=>'2'),
                                                    '20200903225521'=> array ('id_producto'=>'2','correo'=>'1@correo.com', 'comentario'=>'malo', 'valoracion'=>'5'),);
                            
                            echo '<br>';
                            print_r($comentarios);

                            echo '<br>';

                            foreach($comentarios as $clave=>$valor){
                                echo $clave, ')';
                                foreach($valor as $sub_clave=>$sub_valor)
                                    echo $sub_clave, '-',$sub_valor,'|';
                                echo '<br>';
                        }
                        echo '<br>';


 $fp = fopen('comentarios.json','w');
 fwrite($fp,json_encode($a_multi_comentarios));
 fclose($fp);

include_once('includes/footer.php');

?>



                             