<?php

$a_multi_productos = array (
    1 => array ('id_producto' => '1', 
                'nombre' => 'Harry Potter y el caliz de fuego', 
                'descripcion_corta' => 'Tras otro abominable verano con los Dursley, Harry se dispone a iniciar el cuarto curso en Hogwarts, la famosa escuela de magia...',
                'descripcion_larga' => 'Tras otro abominable verano con los Dursley, Harry se dispone a iniciar el cuarto curso en Hogwarts, la famosa escuela de magia y hechicería. A sus catorce años, a Harry le gustaría ser un joven mago como los demás, sin embargo, al llegar al colegio, le espera una gran sorpresa que lo obligará a enfrentarse a los desafíos más temibles de toda su vida',
                'precio' => '$1699',
                'id_editorial' => 3,
                'id_genero' => 6,
                'destacado' => true,
                ),
    2 => array ('id_producto' => '2', 
                'nombre' => 'Tambores de otoño', 
                'descripcion_corta' => 'Despues de huir de Escocia, en 1766 Claire y Jamie emprenden un viaje hacia America.',
                'descripcion_larga' => 'Jamie y Claire no pueden volver a Escocia debido a que Jamie sigue con pedido de captura, por lo que deciden comenzar una nueva vida en las colonias americanas junto a Fergus y el Joven Ian. El grupo se dirige primero a Charleston y luego a Wilmington, antes de establecerse en los inhóspitos cerros boscosos de Carolina del Norte con la esperanza de construir una cabaña autosustentable. La esposa de Fergus, Marsali, se quedó en la isla de Jamaica esperando la llegada del primer hijo de ambos. Al mismo tiempo, Brianna Randall y su pretendiente, el historiador Roger MacKenzie, permanecen seguros en el siglo XX. Ahora huérfana por la partida de su madre al pasado, Brianna lucha por aceptar su pérdida y satisfacer su curiosidad por un padre que nunca ha conocido, solo para descubrir una trágica "historia" que amenaza la felicidad de sus padres en el pasado. Éste descubrimiento hace que Brianna viaje sola a través del tiempo en una misión para salvar a sus padres mientras Roger va tras ella.',
                'precio' => '$1399',
                'id_editorial' => 3,
                'id_genero' => 2,
                'destacado' => false,
                ),                            
    3 => array ('id_producto' => '3', 
                'nombre' => 'La costilla de Adan', 
                'descripcion_corta' => 'Forzado a abandonar su querida Roma natal debido a ciertas irregularidades en el desempeño de su labor policial, Rocco Schiavone...',
                'descripcion_larga' => 'Forzado a abandonar su querida Roma natal debido a ciertas irregularidades en el desempeño de su labor policial, Rocco Schiavone es enviado al valle de Aosta, que pese a estar situado en la península Itálica, para un meridional como él es lo más parecido a aterrizar en Marte. Rodeado de imponentes montañas, atenazado por un frío glacial y desconcertado ante el carácter circunspecto de los habitantes del lugar, Rocco encara su segundo caso con el mismo talante de siempre, irritable y transgresor hasta el límite de lo permisible, pero imbuido de un profundo sentido de la justicia. Cuando una mujer es hallada muerta en su casa y, en la penumbra, se extienden las secuelas de lo que en apariencia ha sido un robo violento, el subjefe Schiavone se resiste a la tentación de creer lo evidente. Una serie de coincidencias y divergencias, sumadas a la ambigüedad de algunos personajes, transformará gradualmente el escenario del crimen en una espesa niebla de misterios.',
                'precio' => '$1049',
                'id_editorial' => 3,
                'id_genero' => 9,
                'destacado' => false,
                ),
    4 => array ('id_producto' => '4', 
                'nombre' => 'La voz del violin', 
                'descripcion_corta' => 'El comisario Salvo Montalbano y su peculiar universo imaginario de Vigàta, en Sicilia, ya no son unos desconocidos en nuestro país.',
                'descripcion_larga' => 'La aparente paz siciliana se ve truncada por el asesinato de una extraña. Una joven hermosa, mujer de un médico boloñés, aparece muerta en el chalet de ambos. Pocas pertenencias la acompañaban en la escena del crimen, aparte de un misterioso violín guardado en su estuche. Su bolsa de joyas se ha esfumado y todas las miradas se centran en un pariente desequilibrado que ha desaparecido la misma noche del crimen. Montalbano, con su parsimonia habitual, inicia la investigación. No cree a nadie, no se fía de nadie. Tras la muerte de un sospechoso, sus superiores dan por cerrado el caso, pero él, ni hablar.
                Transitando los límites de la legalidad, como es su costumbre, Montalbano ha de relacionarse y pactar con los elementos más indeseables y abyectos del hampa, iniciando un viaje a lo más oscuro del alma humana, en el fondo, su territorio predilecto.',
                'precio' => '$1049',
                'id_editorial' => 3,
                'id_genero' => 9,
                'destacado' => false,
                ),
    5 => array ('id_producto' => '5', 
                'nombre' => 'El mar de los monstruos', 
                'descripcion_corta' => 'Desde que sabe que es hijo de un dios y una mortal, Percy Jackson espera que el destino le depare...',
                'descripcion_larga' => 'Desde que sabe que es hijo de un dios y una mortal, Percy Jackson espera que el destino le depare continuas aventuras. Y su expectativa se cumplirá con creces. Aunque el nuevo curso en la Escuela Meriwether transcurre con inusual normalidad, un simple partido de pelota quemada acaba en batalla campal contra una banda de feroces gigantes y el gimnasio del colegio convertido en pasto de las llamas. A partir de ahí las cosas se precipitan: el perímetro mágico que protege el Campamento Mestizo es emponzoñado por un misterioso enemigo y la única seguridad con que contaban los semidioses desaparece. Así, para impedir este daño irreparable, Percy y sus amigos inician la travesía del temible Mar de los Monstruos en busca de lo único que puede salvar el campamento: el Vellocino de Oro. Pero antes Percy descubrirá un secreto acerca de su familia, una inquietante revelación que lo hará preguntarse si ser hijo de Poseidón es un honor o simplemente una broma cruel. 
                El mar de los monstruos es la emocionante continuación de la serie de aventuras Percy Jackson y los Dioses del Olimpo, iniciada con El ladrón del rayo. En pleno siglo XXI, los antiguos dioses griegos han creado un mundo secreto a nuestro alrededor, donde el monte Olimpo se encuentra encima del Empire State y el reino de Hades en el subsuelo de Los Ángeles.',
                'precio' => '$999',
                'id_editorial' => 3,
                'id_genero' => 6,
                'destacado' => true,
                ),
    6 => array ('id_producto' => '6', 
                'nombre' => 'Papeles en el viento', 
                'descripcion_corta' => 'Alejandro, El Mono, ha muerto. Su hermano y sus amigos, un grupo de hierro desde la infancia, apenas se dan...',
                'descripcion_larga' => 'Alejandro, "El Mono", ha muerto. Su hermano y sus amigos, un grupo de hierro desde la infancia, apenas se dan tiempo para el dolor. Les preocupa Guadalupe, la hija del Mono. Quieren darle todo el amor que sentían por su amigo y asegurarle un futuro. Pero en el banco no quedó un peso. El Mono invirtió todo el dinero que tenía en la compra de un jugador de fútbol, un muchacho que prometía pero se quedó en promesa. Ahora está a préstamo en un club zaparrastroso del Interior. Y los trescientos mil dólares que costó su pase, a punto de evaporarse.¿Cómo vender a un delantero que no hace goles? ¿Cómo moverse en un mundo cuyas reglas se desconocen? ¿Cómo seguir siendo amigos si los fracasos van abriendo fisuras en las antiguas lealtades? Fernando, Mauricio y el Ruso, con las escasas herramientas que poseen, desplegarán una serie de estrategias nacidas del ingenio, la torpeza, el desconcierto o la inspiración, para conseguir su objetivo.Eduardo Sacheri demuestra una vez más su capacidad para construir personajes entrañables y contar historias que llegan de inmediato al lector. Papeles en el viento es un canto a la amistad, y una prueba de que el amor y el humor pueden más que la melancolía. Una invitación a pensar sobre el poder de la vida para abrirse paso a través del dolor y poner otra vez en marcha la rueda de los días.',
                'precio' => '$949',
                'id_editorial' => 4,
                'id_genero' => 2,
                'destacado' => true,
                ),
    7 => array ('id_producto' => '7', 
                'nombre' => 'Lo mucho que te ame', 
                'descripcion_corta' => '«Creo que si alguien supiese la historia de mi vida la vería como una vida mal vivida, llena de secretos...',
                'descripcion_larga' => '«Creo que si alguien supiese la historia de mi vida la vería como una vida mal vivida, llena de secretos, traiciones, ocultamientos. Pero en esta historia en la que casi todo lo que hago lo hago mal, me permito creer que hay una cosa, una sola cosa, que hago bien.»
                Lo mucho que te amé es la nueva novela de Eduardo Sacheri. Una historia que nos lleva a la década del 50 en Buenos Aires, en el seno de una familia de origen español.
                Cuenta la historia de Ofelia, una de las cuatro hermanas Fernández Mollé, una muchacha formal, feliz, a punto de casarse. Pero una tarde su vida cambia abruptamente para convertirse en una maraña de sentimientos encontrados: delicia, inquietud, felicidad, incertidumbre, miedo y mucha culpa.
                Con grandes vaivenes interiores y a través de difíciles decisiones, se va convirtiendo en una mujer adulta que enfrenta a su propio modo las circunstancias que le han tocado.',
                'precio' => '$899',
                'id_editorial' => 4,
                'id_genero' => 4,
                'destacado' => false,
                ),
    8 => array ('id_producto' => '8', 
                'nombre' => 'Memorias impuras', 
                'descripcion_corta' => 'El virrey ha muerto y, mientras preparan las exequias, en la ciudad de Álbora esperan un seguro estallido de violencia.',
                'descripcion_larga' => 'El virrey ha muerto y, mientras preparan las exequias, en la ciudad de Álbora esperan un seguro estallido de violencia. En castigo por haber sido la amante y el gran amor del virrey, Junia, la virreyna, encierra a Bérnaba en el calabozo del pueblo, donde cualquiera que lo desee puede pasar la noche con ella.
                Bérnaba, la hermosa, recluida con sus dos hijos y repudiada por todos, resiste y concibe la revolución en su propio cuerpo.
                Todas las razas que habitan el Virreynato se rebelan: los crudos, los mitimaes y los cue cués anhelan la independencia amparados en una profecía y bajo las órdenes de los maestros de la Logia Bagual. Pero las luchas internas entre los revolucionarios, sumadas al terror que encarnan la virreyna y su consejero, Cayo Catarina, y a las aspiraciones al poder de los hacendados, los prestamistas y el Protomedicato desatan una trama tan parecida a la nuestra que se lee con la avidez de quien asiste a su propia historia.',
                'precio' => '$1299',
                'id_editorial' => 4,
                'id_genero' => 4,
                'destacado' => false,
                ),
    9 => array ('id_producto' => '9', 
                'nombre' => 'Ginebra', 
                'descripcion_corta' => '«El agua de la tierra se evapora, el viento raspa las piedras, las hojas caen de los árboles, las palabras...',
                'descripcion_larga' => '«El agua de la tierra se evapora, el viento raspa las piedras, las hojas caen de los árboles, las palabras... ¿a dónde van a parar las palabras?»
                Novela del exilio con reminiscencias punk, novela de soledades y lenguas entrelazadas, Ginebra explora las vetas de la memoria de una niña de 13 años que debe huir del país con su padre y aterriza en una ciudad extraña que, a pesar de lo incierto, le abre un mundo de posibilidades.
                Allí conocerá a Jo Haydn, coleccionista de uñas, hija del responsable del simulacro del big bang, huérfana de madre suicida. También a Oli Dusex, con quien tendrá su primera relación sexual y lo fortuito de su pérdida. El cuarteto se completa con Amo-a-quien-me-ame, una joven drogadicta, dueña de una motocicleta rosa de vetas plateadas que la protagonista roba, desconociendo las gozosas y nostálgicas consecuencias. Estos cuatro jinetes posapocalípticos giran alrededor del lago, como agujas de un reloj sumergido, dando rienda suelta a sus deseos y miedos, apurando la vida en una ciudad con huellas de Jorge Luis Borges y gusto a chocolate, nieve y soledad.
                ¿Cómo se establecen los vínculos más arraigados en la adolescencia? ¿Cuánto de la lengua permite ligarnos, perdernos, equivocarnos, renacer? ¿Qué es lo propio sino la pérdida? Porque así como el exilio puede ser una condena, el encuentro con lo distinto puede convertirse en la travesía de la sorpresa.',
                'precio' => '$979',
                'id_editorial' => 4,
                'id_genero' => 2,
                'destacado' => false,
                ),
    10 => array ('id_producto' => '10', 
                'nombre' => 'Catedrales', 
                'descripcion_corta' => 'Hace treinta años, en un terreno baldío de un barrio tranquilo, apareció descuartizado y quemado el cadáver de una adolescente.',
                'descripcion_larga' => 'Hace treinta años, en un terreno baldío de un barrio tranquilo, apareció descuartizado y quemado el cadáver de una adolescente. La investigación se cerró sin culpables y su familia -de clase media educada, formal y católica- silenciosamente se fue resquebrajando Pero, pasado ese largo tiempo, la verdad oculta saldrá a la luz gracias al persistente amor del padre de la víctima.
                Esa verdad mostrará con crudeza lo que se esconde detrás de las apariencias; la crueldad a la que pueden llevar la obediencia y el fanatismo religioso; la complicidad de los temerosos e indiferentes, y también, la soledad y el desvalimiento de quienes se animan a seguir su propio camino, ignorando mandatos heredados.
                Como en Las viudas de los jueves, en Elena sabe y en Una suerte pequeña, Claudia Piñeiro ahonda con maestría en los lazos familiares, en los prejuicios sociales y en las ideologías e instituciones que marcan los mundos privados, y nos entrega una novela conmovedora y valiente, certera como una flecha clavada en el corazón de este drama secreto.',
                'precio' => '$899',
                'id_editorial' => 4,
                'id_genero' => 9,
                'destacado' => false,
                ),
    11 => array ('id_producto' => '11', 
                'nombre' => 'Cuentos completos', 
                'descripcion_corta' => 'Un hombre que está escribiendo en su despacho es interrumpido por un duende del bosque, un concertista de piano se...',
                'descripcion_larga' => 'Un hombre que está escribiendo en su despacho es interrumpido por un duende del bosque, un concertista de piano se dispone a poner fin a su  carrera, un barbero afeita al hombre que lo torturó, un soñador tímido hace un pacto con el Diablo...
                Los sesenta y ocho relatos de Vladimir Nabokov que se incluyen en esta  edición definitiva de su obra cuentística, preparada por su hijo Dmitri, permiten disfrutar de su inconmensurable virtuosismo literario: de sus piruetas temáticas y formales, de sus inquietantes ambigüedades, de su elegante manejo del idioma, de la presencia de los  temas ?como el del doble? que lo fascinaban y de los muchos lugares que dejaron huella en él: la Rusia de su infancia, la Inglaterra de sus años de estudiante, la Alemania y la Francia del exilio y después esos Estados Unidos que siempre observó con sagaz y nada complaciente mirada de europeo.
                La incorporación de este libro al catálogo de Anagrama permite añadir una pieza más al puzle de la rica producción literaria de Nabokov, del  que hemos publicado el grueso de su obra novelística. Y, como en las novelas, en estos cuentos brilla la inagotable inventiva de uno de los  escritores auténticamente imprescindibles del siglo XX.',
                'precio' => '$2950',
                'id_editorial' => 5,
                'id_genero' => 8,
                'destacado' => true,
                ),
    12 => array ('id_producto' => '12', 
                'nombre' => '>Mi corazon sedicioso', 
                'descripcion_corta' => 'Arundhati Roy investiga y denuncia. Los imprescindibles ensayos políticos  de la escritora india.',
                'descripcion_larga' => 'Arundhati Roy investiga y denuncia.  Los imprescindibles ensayos políticos  de la escritora india.
                Este volumen reúne una amplia selección de los mejores textos de carácter político y social escritos por la autora. En estas páginas aborda temas como la retórica belicista que justifica guerras; la política exterior de los imperios–americano y soviético–; la corrupción política; el cambio climático; el capitalismo depredador; el terrorismo; los desequilibrios sociales de la India, ese país que vive al mismo tiempo en varios siglos, anclado en el pasado y proyectado hacia el futuro; los conflictos territoriales entre la India y Pakistán; el poder de las élites, el control de la tierra y los indiscriminados desplazamientos de población para la construcción de grandes presas; los claroscuros de la figura de Gandhi; la deriva nacionalista en la India; la energía nuclear utilizada con fines bélicos; las grietas de la democracia y la represión de la disidencia',
                'precio' => '$1799',
                'id_editorial' => 5,
                'id_genero' => 7,
                'destacado' => false,
                ),
    13 => array ('id_producto' => '13', 
                'nombre' => 'Amelie Nothomb', 
                'descripcion_corta' => 'Hija de diplomatico, Amelie Nothomb paso buena parte de su ninez en Oriente. De ahi le quedo una pasion por...',
                'descripcion_larga' => 'Hija de diplomatico, Amelie Nothomb paso buena parte de su ninez en Oriente. De ahi le quedo una pasion por Japon mezcla de deslumbramiento y encontronazo, de fascinacion por una cultura y choque con unas pautas sociales desquiciantes y humillantes. Este libro reune seis novelas autobiograficas de la escritora belga, en las que evoca episodios de su infancia y adolescencia la crueldad, la inocencia, el desconcierto, el hambre de conocer vividas en Oriente, y tambien varios viajes de regreso a Japon en los que se enfrenta al delirante mundo empresarial nipon, al amor de un joven avido lector de Stendhal, al reencuentro con la ninera que la cuido cuando era nina, a recorridos que la llevan del bullicioso Tokio a Hiroshima y al espiritual Monte Fuji. / This book combines six autobiographical novels by the Belgian writer, covering episodes from her childhood, adolescence, living in the East, and several trips to Japan where she faces their delirious business world, reunites with the nanny who cared for her as a child, and journeys to Mount Fuji.',
                'precio' => '$2950',
                'id_editorial' => 5,
                'id_genero' => 5,
                'destacado' => false,
                ),
    14 => array ('id_producto' => '14', 
                'nombre' => 'Se busca una mujer', 
                'descripcion_corta' => 'En este libro ambientado en Los Ángeles se nota la continua presencia de la gran urbe en toda la escritura...',
                'descripcion_larga' => 'En este libro ambientado en Los Ángeles se nota la continua presencia de la gran urbe en toda la escritura de Charles Bukowski, ciudad infernal, a pesar de estar situada en medio de paraíso californiano, sueño de todo pobre ciudadano USA, con sus naranjas, su sol y su vino, vino del que Bukowski da buena cuenta toda su vida, como el whisky, como la cerveza, que habrán de ser, inevitablemente, su fuente de inspiración.',
                'precio' => '$895',
                'id_editorial' => 5,
                'id_genero' => 2,
                'destacado' => false,
                ),
    15 => array ('id_producto' => '15', 
                'nombre' => 'Un hombre enamorado', 
                'descripcion_corta' => 'De ser hijo a ser padre. Éste es el paso del autor en la segunda parte de las seis que conforman...',
                'descripcion_larga' => 'De ser hijo a ser padre. Éste es el paso del autor en la segunda parte de las seis que conforman Mi lucha, esa inmensa novela autobiográfica que la crítica ha descrito como «un proyecto demencial que sólo los verdaderos genios pueden alcanzar». Karl Ove deja a su mujer y se marcha a Estocolmo. Allí se hace amigo de Geir, otro noruego, intelectual y fanático del boxeo. Y vuelve a encontrarse con Linda, una poeta que le había fascinado en un encuentro de escritores, y que será su segunda mujer. Su mundo cambia mientras él escribe y cuenta cómo es volverse a enamorar, los goces y los engorros de la paternidad, la necesidad de escribir, la cotidianeidad de la vida en familia o el cómico fracaso de sus vacaciones, la humillación de las clases de preparación al parto, las peleas con los vecinos... Knausgård escribe con una veracidad punzante sobre los instantes que componen una vida, la de un hombre que anhela con igual intensidad la soledad y el amor.',
                'precio' => '$1095',
                'id_editorial' => 5,
                'id_genero' => 2,
                'destacado' => false,
                ),
    16 => array ('id_producto' => '16', 
                'nombre' => 'IT', 
                'descripcion_corta' => '¿Quien o que mutila y mata a los niños de un pequeño pueblo norteamericano? ¿Por que llega cíclicamente el horror...',
                'descripcion_larga' => '¿Quien o que mutila y mata a los niños de un pequeño pueblo norteamericano?
                ¿Por que llega cíclicamente el horror a Derry en forma de un payaso siniestro que va sembrando la destrucción a su paso?
                Esto es lo que se proponen averiguar los protagonistas de esta novela. Tras veintisiete años de tranquilidad y lejanía, una antigua promesa infantil les hace volver al lugar en el que vivieron su infancia y juventud como una terrible pesadilla. Regresan a Derry para enfrentarse con su pasado y enterrar definitivamente la amenaza que los amargó durante su niñez.
                Saben que pueden morir, pero son conscientes de que no conocerán la paz hasta que aquella cosa sea destruida para siempre.',
                'precio' => '$1899',
                'id_editorial' => 2,
                'id_genero' => 3,
                'destacado' => true,
                ),
    17 => array ('id_producto' => '17', 
                'nombre' => 'Memorias del aguila y del jaguar', 
                'descripcion_corta' => 'ISABEL ALLENDE nos invita a acompañar a Alex Cold y a su abuela Kate en sus aventuras por el mundo.',
                'descripcion_larga' => 'ISABEL ALLENDE nos invita a acompañar a Alex Cold y a su abuela Kate en sus aventuras por el mundo. En La Ciudad de las Bestias, se internan en la selva amazónica en busca de una extraña bestia semihumana; en El Reino del Dragón de Oro, descubren la sabiduría oriental en un recóndito reino del Himalaya, a la vez que hacen frente a unos desalmados traficantes de antigüedades; El Bosque de los Pigmeos nos sitúa en el corazón de una África misteriosa en la que se dan cita la solidaridad y la magia.',
                'precio' => '$1599',
                'id_editorial' => 2,
                'id_genero' => 6,
                'destacado' => false,
                ),
    18 => array ('id_producto' => '18', 
                'nombre' => 'Diarios', 
                'descripcion_corta' => 'Este volumen invita al lector a conocer el lado más íntimo del padre de la literatura del siglo XX...',
                'descripcion_larga' => 'Este volumen invita al lector a conocer el lado más íntimo del padre de la literatura del siglo XX a través de sus diarios, legajos y cuadernos de viaje, editados por orden cronológico y respetando fielmente los manuscritos originales del escritor checo, sin las supresiones y censuras de Max Brod.
                Estas páginas ofrecen una panorámica de la vida de Kafka, sus paseos por Praga, sus sueños, sus sentimientos hacia el padre idolatrado y la mujer con la que no lograba casarse, su contienda personal con la culpa y la percepción de sí mismo como un paria, en una rendición de cuentas de una intensidad casi insoportable.',
                'precio' => '$1699',
                'id_editorial' => 2,
                'id_genero' => 5,
                'destacado' => false,
                ),
    19 => array ('id_producto' => '19', 
                'nombre' => 'Grandes esperanzas', 
                'descripcion_corta' => '«El corazón humano es un instrumento de muchas cuerdas; el perfecto conocedor de los hombres las sabe hacer vibrar todas...',
                'descripcion_larga' => '«El corazón humano es un instrumento de muchas cuerdas; el perfecto conocedor de los hombres las sabe hacer vibrar todas, como un buen músico.» Charles Dickens
                Kent, Inglaterra, finales del siglo XIX. El huérfano Pip vive una existencia humilde con su hermana y su cuñado, a quien ayuda en su taller de herrería. Cuando la rica señorita Havisham requiere a Pip como acompañante de ella y de su bella hija, el joven se dará cuenta de las penurias de su clase social y deseará cada vez con más fuerza subir posiciones en el escalafón social. Pip recibirá entonces la visita de un abogado de Londres, quien le informará de que un benefactor anónimo le quiere convertir en un caballero. Sin embargo, Pip descubrirá que el valor de la amistad y de la moral no se puede comprar con dinero.',
                'precio' => '$1599',
                'id_editorial' => 2,
                'id_genero' => 5,
                'destacado' => false,
                ),
    20 => array ('id_producto' => '20', 
                'nombre' => 'Tatiana y Alexander', 
                'descripcion_corta' => 'Embarazada, enferma y absolutamente desolada, Tatiana ha logrado llegar a Estados Unidos. Entregada a la fuerza de las circunstancias y...',
                'descripcion_larga' => 'Embarazada, enferma y absolutamente desolada, Tatiana ha logrado llegar a Estados Unidos. Entregada a la fuerza de las circunstancias y alejada de su convulsionada tierra, la joven comenzará una nueva existencia con la secreta ilusión de que, en alguna parte, el hombre al que ama sea capaz de vencer a las oscuras garras del destino.
                Mientras, Alexander sufre el hostigamiento de las fuerzas represoras en las gelidas tierras de la Unión Sovietica, y tan solo el recuerdo de su esposa, junto con la velada esperanza de que siga con vida, alimenta su espíritu ante la adversidad.
                Al tiempo que la contienda llega a su final, ambos lucharán contra sus destinos y la desesperación en busca del amor perdido y la inquebrantable esperanza del reencuentro.',
                'precio' => '$1579',
                'id_editorial' => 2,
                'id_genero' => 4,
                'destacado' => false,
                ),
    21 => array ('id_producto' => '21', 
                'nombre' => 'Amores prohibidos', 
                'descripcion_corta' => 'Manuel fue acercándose de a poco a la damita de ojos negros, hasta que sus labios comenzaron a susurrarle frases...',
                'descripcion_larga' => 'Manuel fue acercándose de a poco a la damita de ojos negros, hasta que sus labios comenzaron a susurrarle frases bonitas al oído. Los ojos de Maruja se entornaron y sonrió levemente. ‘El joven americano sí que sabe hablarle a una dama. No me equivoqué. Ahora quiero su cuerpo pegado al mío’, pensó.” El primer romántico del Río de la Plata fue un incomprendido. Manuel Belgrano no era militar y debió ocupar un rol inesperado. Además de ser un intelectual de avanzada, fue responsable de cambios políticos y sociales mal vistos por lo más rancio de la sociedad porteña. Tampoco cumplía con las normas de la masculinidad de su época: no era autoritario ni arremetedor. Por el contrario, fue un hombre sensible, refinado, elegante. Adorado por las mujeres, vivió romances tórridos con españolas, argentinas y francesas. Sin embargo, fueron tres las que marcaron su piel a fuego. Con la primera, Pepa Ezcurra, una jovencita de la sociedad porteña, mantuvo una relación clandestina que no pudo hacerse pública y de la cual nació un hijo criado por el mismísimo Juan Manuel de Rosas. En su paso por Europa fue una francesa de armas tomar la que robó su corazón: Isabel Pichegru. Ya de adulto, se deja seducir por una “niña” de la burguesía tucumana, Dolores Helguero. Tampoco se compromete con ella, pero viven una pasión que también trajo una hija al mundo. Manuel Belgrano murió solo y pobre. Nunca supo que el “hijo” de Rosas era suyo y apenas conoció a Mónica Manuela, su hija mujer. Mucho es lo que se ha escrito sobre Manuel Belgrano, y un sinfín de versiones intentó recomponer una figura patria que poco tiene que ver con ese hombre de carne y hueso presa de sus deseos más ocultos. Hacia esa zona de luces y sombras parte Florencia Canale en su nueva novela, Amores secretos. Un libro que reconstruye la vida privada del prócer y que a la vez confirma a su autora como una de las más innovadoras en el género de la novela histórica en la Argentina.',
                'precio' => '$1330',
                'id_editorial' => 1,
                'id_genero' => 4,
                'destacado' => true,
                ),
    22 => array ('id_producto' => '22', 
                'nombre' => 'El maestro del prado', 
                'descripcion_corta' => 'Descubre de la mano de Javier Sierra los secretos que se ocultan tras las pinturas más importantes del Museo del Prado.',
                'descripcion_larga' => 'Descubre de la mano de Javier Sierra los secretos que se ocultan tras las pinturas más importantes del Museo del Prado.
                Al más puro estilo de los relatos de enigmas de Javier Sierra.El maestro del Prado presenta un apasionante recorrido por las historias más desconocidas y secretas de una de las pinacotecas más importantes del mundo, el Museo del Prado.
                Una historia fascinante de cómo un aprendiz de escritor aprendió a mirar cuadros y a entender unos mensajes ocultos que difieren de la ortodoxia de la Iglesia católica, una institución que en el Renacimiento era visto más como opresores que como espiritual.
                Una nueva obra que entusiasmará a los miles de seguidores de Javier Sierra.',
                'precio' => '$1560',
                'id_editorial' => 1,
                'id_genero' => 4,
                'destacado' => false,
                ),
    23 => array ('id_producto' => '23', 
                'nombre' => 'Lo que me costo el amor de Laura', 
                'descripcion_corta' => 'Esta operéta criolla en dos actos, cuenta la historia de Manuel, que al conocer a Laura se enamora desesperadamente.',
                'descripcion_larga' => 'Esta operéta criolla en dos actos, cuenta la historia de Manuel, que al conocer a Laura se enamora desesperadamente. Laura le pide que para conquistarla obtenga la llave del amor. Dicha llave se encuentra en algúnsítio del Barrio del Dolor, "un distrito siniestro del que nadie ha regresado jamás".
                Un locutor guiará al público en este viaje dantesco, donde el enamorado se encontrará con vecinos muy particulares, que ayudarán a conseguir la llave. Esta historia entre tangos y ritmos criollos denotan la alta capacidad creativa musical de su autor: Alejandro Dolina.',
                'precio' => '$1040',
                'id_editorial' => 1,
                'id_genero' => 1,
                'destacado' => false,
                ),
    24 => array ('id_producto' => '24', 
                'nombre' => 'Secret', 
                'descripcion_corta' => 'Cassie Robichaud, una joven viuda, es  introducida en S.E.C.R.E.T., un selecto club underground de Nueva Orleans que ayuda a las mujeres...',
                'descripcion_larga' => 'Cassie Robichaud, una joven viuda, es  introducida en S.E.C.R.E.T., un selecto club underground de Nueva Orleans que ayuda a las mujeres a disfrutar al máximo de su sexualidad. Asesorada por una matriarca clandestina, Cassie es invitada a experimentar sus fantasías más íntimas siempre que respete los requisitos del club',
                'precio' => '$239',
                'id_editorial' => 1,
                'id_genero' => 2,
                'destacado' => false,
                )
);
echo '<pre>';
print_r($a_multi_productos);
echo '</pre>';

$fp = fopen('detalleproductos.json','w');
fwrite($fp,json_encode($a_multi_productos));
fclose($fp);


?>